name: Sync to Hugging Face Hub
on:
  push:
    branches: [main] # Change this to master if your GitHub branch is named master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HF Space
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: bhuuuuu/Career-Trajectory-Analysis
          hf_token: ${{ secrets.HF_TOKEN }}
